"""add rename folder to handle column




Revision ID: 740917e6a580
Revises: fd616fa93721
Create Date: 2023-03-13 16:05:43.678785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740917e6a580'
down_revision = 'fd616fa93721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handle', sa.String(length=120), nullable=True))
        batch_op.drop_column('folder')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('handle')

    # ### end Alembic commands ###
